#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-capybara
Version  : 2.7.1
Release  : 12
URL      : https://rubygems.org/downloads/capybara-2.7.1.gem
Source0  : https://rubygems.org/downloads/capybara-2.7.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-fuubar
BuildRequires : rubygem-launchy
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-pry
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-sinatra
BuildRequires : rubygem-yard

%description
# Capybara
[![Build Status](https://secure.travis-ci.org/jnicklas/capybara.svg)](https://travis-ci.org/jnicklas/capybara)
[![Dependency Status](https://gemnasium.com/jnicklas/capybara.svg)](https://gemnasium.com/jnicklas/capybara)
[![Code Climate](https://codeclimate.com/github/jnicklas/capybara.svg)](https://codeclimate.com/github/jnicklas/capybara)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n capybara-2.7.1
gem spec %{SOURCE0} -l --ruby > rubygem-capybara.gemspec

%build
gem build rubygem-capybara.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
capybara-2.7.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/capybara-2.7.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/History.md
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/License.txt
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/cucumber.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/driver/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/driver/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/actions.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/document_matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/element.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/node/simple.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/base_query.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/current_path_query.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/match_query.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/selector_query.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/text_query.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/title_query.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/query.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rack_test/browser.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rack_test/css_handlers.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rack_test/driver.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rack_test/form.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rack_test/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rspec/features.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/rspec/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/selector/filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/selenium/driver.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/selenium/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/server.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/session/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/fixtures/another_test_file.txt
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/fixtures/capybara.jpg
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/fixtures/test_file.txt
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/public/jquery-ui.js
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/public/jquery.js
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/public/test.js
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/accept_alert_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/accept_confirm_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/accept_prompt_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/all_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/assert_current_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/assert_selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/assert_text.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/assert_title.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/attach_file_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/body_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/check_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/choose_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/click_button_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/click_link_or_button_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/click_link_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/current_scope_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/current_url_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/dismiss_confirm_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/dismiss_prompt_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/element/assert_match_selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/element/match_css_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/element/match_xpath_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/element/matches_selector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/evaluate_script_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/execute_script_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/fill_in_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/find_button_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/find_by_id_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/find_field_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/find_link_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/find_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/first_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/go_back_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/go_forward_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_button_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_css_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_current_path_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_field_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_link_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_select_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_selector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_table_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_text_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_title_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/has_xpath_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/headers.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/html_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/node_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/reset_session_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/response_code.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/save_and_open_page_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/save_and_open_screenshot_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/save_page_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/save_screenshot_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/screenshot_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/select_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/selectors_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/source_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/text_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/title_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/uncheck_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/unselect_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/visit_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/window/become_closed_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/window/current_window_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/window/open_new_window_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/window/switch_to_window_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/window/window_opened_by_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/window/window_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/window/windows_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/window/within_window_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/within_frame_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/session/within_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/test_app.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/buttons.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/fieldsets.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/form.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/frame_child.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/frame_one.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/frame_parent.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/frame_two.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/header_links.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/host_links.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/path.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/popup_one.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/popup_two.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/postback.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/tables.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_base_tag.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_count.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_hover.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_html.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_html_entities.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_js.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_scope.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_simple_html.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_slow_unload.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_title.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_unload_alert.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/with_windows.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/spec/views/within_frames.erb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/lib/capybara/window.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/basic_node_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/capybara_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/dsl_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/fixtures/selenium_driver_rspec_failure.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/fixtures/selenium_driver_rspec_success.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/rack_test_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/result_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/rspec/features_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/rspec/matchers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/rspec/scenarios_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/rspec/views_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/rspec_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/selector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/selenium_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/selenium_spec_chrome.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/server_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/capybara-2.7.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/capybara-2.7.1.gemspec
